baseURL = 'https://wreckd.runs.nz/'
languageCode = 'en-nz'
title = "WREC'kd – Wellington Trail & Endurance Running Club | New Zealand"
theme = 'ananke'

[params]
  description = "WREC'kd is Wellington's trail and endurance running club. Grassroots events in the Orongorongo, Remutaka, Tararua and Aorangi ranges. Join the Wilderness Running and Endurance Collective and run the Mukamuka Munter, Aorangi Undulator and more across the lower North Island."
  background_color_class = "bg-white"
  body_classes = "bg-white"
  featured_image = ""
  show_reading_time = false
  custom_css = ["custom.css"]

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "Fixtures"
    url = "/fixtures/"
    weight = 20

  [[menu.main]]
    name = "Faq"
    url = "/faq/"
    weight = 20
  [[menu.main]]
    name = "Join"
    url = "/join/"
    weight = 30
